#pragma once

// Self-contained device page. The state and actions stay on the ESPHome node.
static const char STS3215_DASHBOARD_HTML[] PROGMEM = R"stsweb(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Servo Settings</title><style>
:root{color-scheme:dark;font:15px/1.4 system-ui,sans-serif;background:#0b1220;color:#e9f1fc}
*{box-sizing:border-box}body{margin:0}main{max-width:1180px;margin:auto;padding:24px 18px 70px}
header{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:24px}
h1{font-size:clamp(24px,4vw,36px);line-height:1.1;margin:4px 0}h2{margin:0;font-size:22px}
.eyebrow{color:#76adf8;text-transform:uppercase;letter-spacing:.14em;font-size:11px;font-weight:800}
.muted{color:#9babc3}.connection{border:1px solid #344760;border-radius:100px;padding:6px 12px;font-size:13px}
.connection.live{color:#91e2a4;border-color:#36744b}.stack{display:grid;gap:18px}
.card{background:#111d30;border:1px solid #273b56;border-radius:18px;padding:20px;box-shadow:0 12px 30px #0003}
.cardhead{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:17px}
.badge{font-size:12px;border-radius:100px;padding:5px 10px;background:#24344d;color:#acc5e7}
.badge.ok{background:#123f2e;color:#8ce0aa}.badge.warn{background:#50341d;color:#ffc58b}
.groupControls,.tiltChoices,.legend,.settings,.telemetry{display:flex;flex-wrap:wrap;gap:8px;align-items:center}
button,select,input{font:inherit}button{background:#1d3350;border:1px solid #436184;border-radius:9px;color:#e7f2ff;padding:9px 12px;cursor:pointer}
button:hover:not(:disabled){background:#28507a;border-color:#73aef2}button:disabled{opacity:.45;cursor:not-allowed}
button.primary{background:#2562a5;border-color:#5ba1f0}button.danger{background:#492b32;border-color:#96505b;color:#ffd6db}
button.small{padding:6px 10px;font-size:13px}button.active{border-color:#5db0f8;background:#244b73}
input,select{background:#0b1727;border:1px solid #405873;border-radius:8px;color:#f3f8ff;padding:7px 9px}
input[type=number]{width:82px}label{display:inline-flex;align-items:center;gap:7px;color:#b8c9df}
.calGrid{display:grid;grid-template-columns:minmax(230px,1fr) minmax(210px,.85fr) minmax(310px,1.15fr);gap:14px;align-items:stretch}
.manual,.plotCol,.readout{background:#0c1828;border:1px solid #2b3e56;border-radius:14px;padding:16px;min-width:0}
.panelTitle{font-size:20px;font-weight:800;margin:0 0 15px}.switchRow{display:flex;justify-content:space-between;align-items:center;gap:8px;background:#152438;border:1px solid #314963;border-radius:10px;padding:10px 12px;margin-bottom:13px}.switchRow input{accent-color:#168af5;width:21px;height:21px}.panelSub{font-size:15px;font-weight:800;margin:14px 0 8px;padding-top:12px;border-top:1px solid #32445a}
.manual{display:flex;flex-direction:column;gap:12px}
.manualRow{display:grid;grid-template-columns:44px 1fr;gap:8px}.manualRow button{min-height:42px}.manualRow .arrow{font-size:19px;padding:6px}
.jogBox{margin-top:6px}.jogBox input{width:94px}.reset{margin-top:4px;width:100%}
.stopButton{background:#59343a;border-color:#a85d67}.positionRow{background:#142337;border:1px solid #2e465f;border-radius:11px;padding:12px;margin-bottom:9px}.positionRow header{margin:0 0 8px;align-items:center}.positionRow strong{font-size:18px}.positionRow .kind{font-size:11px;border:1px solid currentColor;border-radius:6px;padding:2px 6px}.positionRow .value{font-size:24px;font-weight:800;font-variant-numeric:tabular-nums}.positionRow input{width:100%;font-size:20px}.positionRow .green{color:#75e5a1}.positionRow .blue{color:#5aaaff}.savePositions{width:100%;margin-bottom:9px}.stateLine{background:#142337;border-radius:9px;padding:8px 11px;display:flex;justify-content:space-between;margin-bottom:7px}
.plotCol{display:flex;flex-direction:column;align-items:stretch;gap:9px}.plotCol>.primary{min-height:42px}
.plotWrap{height:320px;position:relative;margin:4px 12px 0 25px}
.track{position:absolute;left:35px;right:35px;top:0;bottom:0;background:#0a1524;border:1px solid #527091;border-radius:8px;overflow:hidden}
.fill{position:absolute;left:0;right:0;bottom:0;background:linear-gradient(0deg,#2169bd99,#43b5f766);height:0;transition:height .35s}
.mark{position:absolute;left:0;right:0;height:0;border-top:2px solid;z-index:2;transform:translateY(-1px)}
.mark.green{border-color:#75e5a1}.mark.blue{border-color:#5aaaff}.mark.red{border-color:#ff6b72}
.mark.striped{height:6px;border:0;background:repeating-linear-gradient(90deg,#ff6b72 0 8px,#75e5a1 8px 16px)}
.mark.target{border-style:dashed}.mark.current{border-color:#bdeeff;border-width:3px;z-index:4}
.markLabel{position:absolute;font-size:10px;font-weight:800;letter-spacing:.06em;z-index:5;transform:translateY(-50%);background:#111d30;padding:0 3px}
.markLabel.left{left:0}.markLabel.right{right:0}.markLabel.green{color:#75e5a1}.markLabel.blue{color:#5aaaff}.markLabel.red{color:#ff6b72}
.direction{display:flex;flex-direction:column;gap:5px;font-size:12px}.direction select{width:100%;font-size:13px}
.readout{display:flex;flex-direction:column;gap:13px}.liveLine{padding:10px 12px;background:#172a42;border-radius:10px;display:flex;justify-content:space-between;gap:10px}
.livePair{display:grid;grid-template-columns:1fr 1fr;gap:8px}.livePair .liveLine{display:flex;flex-direction:column;gap:3px}.livePair strong{font-size:20px;font-variant-numeric:tabular-nums}
.values{display:grid;grid-template-columns:1fr auto auto;gap:0;border:1px solid #314a68;border-radius:11px;overflow:hidden}
.values>*{padding:11px 10px;border-bottom:1px solid #314a68}.values>*:nth-last-child(-n+3){border-bottom:0}
.values .head{font-size:11px;color:#9eb1ca;text-transform:uppercase;letter-spacing:.05em;background:#18283f}
.values .num{text-align:right;font-variant-numeric:tabular-nums}.values .rowlabel{font-weight:700}
.values .green{color:#80e3a7}.values .blue{color:#77b6ff}
.legend{font-size:12px;color:#b7c8de;gap:12px;margin-top:auto}.key{display:inline-flex;align-items:center;gap:5px}.swatch{width:14px;border-top:3px solid}
.details{margin-top:19px;padding-top:17px;border-top:1px solid #293f5b}.details summary{cursor:pointer;color:#c3d8f2;font-weight:700}
.detailGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin-top:14px}
.metric{background:#0b192b;border-radius:10px;padding:9px 11px}.metric small{display:block;color:#91a8c2}.metric strong{font-variant-numeric:tabular-nums}
.settings{margin-top:16px}.settings label{background:#0b192b;border-radius:9px;padding:7px 9px}.settings button{padding:7px 10px}
.note{font-size:12px;color:#9aacc4;margin-top:12px}.toast{position:fixed;bottom:15px;left:50%;transform:translateX(-50%);background:#244363;border:1px solid #74b5f5;border-radius:9px;padding:9px 14px;z-index:20}
/* Full control panels follow the supplied three-column reference. */
:root{background:#0e1215;color:#f3f6fa}main{max-width:1500px;padding:24px 20px 70px}.card{background:transparent;border:0;box-shadow:none;padding:0 0 20px}.cardhead{padding:0 3px}.manual,.plotCol,.readout{background:#171c1f;border:1px solid #323d42;border-radius:12px;padding:20px;box-shadow:inset 0 0 30px #ffffff05}.calGrid{grid-template-columns:minmax(280px,1fr) minmax(250px,.85fr) minmax(310px,1fr);gap:14px}.panelTitle{font-size:25px;margin-bottom:18px}.switchRow{background:#1b2226;border-color:#344047;color:#f3f6fa;font-size:18px;min-height:60px;padding:13px 15px}.switchRow input{appearance:none;width:58px;height:32px;border:0;border-radius:100px;background:#45525b;position:relative;cursor:pointer;flex:none}.switchRow input:after{content:'';position:absolute;top:3px;left:3px;width:26px;height:26px;background:white;border-radius:50%;transition:left .15s}.switchRow input:checked{background:#168dfa}.switchRow input:checked:after{left:29px}
.manualRow{grid-template-columns:minmax(76px,.55fr) minmax(130px,1fr);gap:12px}.manualRow button{height:125px;background:#272e32;border-color:#48555b;border-radius:11px;font-size:19px;font-weight:650}.manualRow .arrow{font-size:38px}.manualRow button:hover:not(:disabled){background:#344148}.manualRow .stopButton{background:#303236}.sliderStack{border-top:1px solid #485359;margin-top:8px;padding-top:15px;display:grid;gap:12px}.sliderBox{background:#1b2226;border:1px solid #354147;border-radius:12px;padding:12px 14px}.sliderHead{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:10px;font-weight:650}.sliderValue{color:#20a0ff;font-size:17px;font-variant-numeric:tabular-nums}.sliderBox input[type=range]{display:block;width:100%;padding:0;border:0;background:none;accent-color:#1597f5;cursor:pointer}.rangeEnds{display:flex;justify-content:space-between;color:#aebed0;font-size:12px;margin-top:5px}
.plotCol>.primary,.plotCol>.danger{width:100%;min-height:59px;font-size:18px;font-weight:700}.plotCol>.primary{background:#087def;border-color:#188df6}.plotCol>.danger{background:#d8262d;border-color:#eb454b}.statusStack{display:grid;gap:8px;margin:5px 0 8px}.statusBox{background:#1b2226;border:1px solid #344047;border-radius:10px;padding:9px 12px;display:flex;gap:12px;align-items:center}.statusIcon{width:31px;height:31px;border-radius:50%;background:#798895;color:#111;display:grid;place-items:center;font-size:18px;font-weight:900}.statusBox.good .statusIcon{background:#10dc76}.statusBox .statusText{display:flex;flex-direction:column}.statusBox small{color:#c7d1dd}.statusBox strong{color:#eaf1fa}.statusBox.good strong{color:#27e787}.plotTop,.plotBottom{text-align:center;color:#c7d8f3;font-size:13px;line-height:1.25}.plotWrap{height:500px;margin:5px 35px 7px 40px}.track{left:44px;right:44px;background:#20292d;border:2px solid #adbcc5}.fill{background:linear-gradient(0deg,#0d508999,#1ca6f3)}.mark{left:44px;right:44px;border-width:4px}.markLabel{background:#171c1f;font-size:12px;letter-spacing:0}.markLabel.left{left:auto;right:0}.markLabel.right{right:0}.direction{font-size:15px}.direction select{font-size:16px;background:#1a2024;min-height:50px}
.readout .liveLine{background:#1b2226;border:1px solid #354147}.positionRow{background:#1b2226;border-color:#344047;padding:15px;margin-bottom:12px}.positionRow .value{font-size:27px}.positionRow header{margin-bottom:8px}.positionRow .kind{font-size:12px}.telemetryGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.telemetryGrid .metric{background:#1b2226;border:1px solid #354147;padding:12px}.metric strong{font-size:25px}.meter{height:8px;border-radius:99px;background:#34414c;overflow:hidden;margin:12px 0 5px}.meter span{display:block;height:100%;background:#1597f5;border-radius:99px;width:0}.meterEnds{display:flex;justify-content:space-between;color:#aebed0;font-size:11px}.panelSub{font-size:19px}.legend{display:none}.details{margin-top:10px}.details summary{font-size:13px}.settings{display:none}
.tiltBox{background:#1b2226;border:1px solid #354147;border-radius:12px;padding:12px 14px}.tiltBox .sliderHead{margin-bottom:10px}.tiltChoices{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:5px}.tiltChoices button{padding:9px 0;font-size:13px;font-weight:700}
.scaleTick{position:absolute;left:0;z-index:5;width:37px;text-align:right;transform:translateY(-50%);color:#c7d8f3;font-size:12px;font-variant-numeric:tabular-nums}.scaleTick:after{content:'';position:absolute;right:-9px;top:50%;width:5px;border-top:2px solid #c7d8f3}.scaleTick.top{top:0;transform:translateY(-25%)}.scaleTick.q3{top:25%}.scaleTick.mid{top:50%}.scaleTick.q1{top:75%}.scaleTick.bottom{top:100%;transform:translateY(-75%)}
.mark{border:0;height:4px;background:currentColor;border-radius:8px;transform:translateY(-2px)}.mark.green{color:#75e5a1}.mark.blue{color:#5aaaff}.mark.red{color:#ff6b72}.mark.current{background:#bdeeff;height:3px;transform:translateY(-1px)}.mark.target{background:repeating-linear-gradient(90deg,#5aaaff 0 9px,transparent 9px 14px)}.mark.edgeTop{height:9px;border-radius:8px 8px 2px 2px;transform:none}.mark.edgeBottom{height:9px;border-radius:2px 2px 8px 8px;transform:translateY(-9px)}.mark.striped{background:repeating-linear-gradient(90deg,#ff6b72 0 8px,#75e5a1 8px 16px)}.markLabel{padding:1px 3px}.markLabel:before{content:'';position:absolute;left:-11px;top:50%;transform:translateY(-50%);border-top:6px solid transparent;border-bottom:6px solid transparent;border-right:9px solid currentColor}
.calGrid{grid-template-columns:repeat(3,minmax(0,1fr))}.plotWrap{margin-left:0;margin-right:0;height:540px}.track{left:44px;right:100px}.mark{left:44px;right:100px}.mark.edgeTop,.mark.edgeBottom{left:53px;right:109px;height:4px;border-radius:0}.mark.edgeTop{transform:none}.mark.edgeBottom{transform:translateY(-4px)}.scaleTick:after{right:0;width:4px}.scaleTick.top{top:2px}.scaleTick.bottom{top:calc(100% - 2px)}.scaleTick.top:after,.scaleTick.bottom:after{display:none}.plotTop,.plotBottom{margin-left:44px;margin-right:100px}.direction{width:100%;align-items:center;align-self:center}.direction select{width:100%}
.markAnnotation{position:absolute;right:0;width:100px;z-index:5;transform:translateY(-50%);height:18px;display:flex;align-items:center;white-space:nowrap;font-size:12px;font-weight:800;font-variant-numeric:tabular-nums}.markAnnotation.green{color:#75e5a1}.markAnnotation.blue{color:#5aaaff}.markAnnotation.red{color:#ff6b72}.markPointer{width:0;height:0;flex:none;border-top:6px solid transparent;border-bottom:6px solid transparent;border-right:9px solid currentColor;margin-left:2px;margin-right:5px}.markNumber{line-height:18px}.markLabel{display:none}
.manual .sliderStack{margin-top:auto}.direction{margin-top:auto;min-height:96px;justify-content:center;gap:6px}
.plotWrap .track{left:90px;right:90px}.plotWrap .mark{left:90px;right:90px}.plotWrap .mark.edgeTop,.plotWrap .mark.edgeBottom{left:99px;right:99px}.plotWrap .markAnnotation{right:0;width:90px}.plotWrap .scaleTick{left:25px;width:45px}.plotTop,.plotBottom{margin-left:90px;margin-right:90px}
.plotWrap .scaleTick.top{top:12px;transform:translateY(-50%)}.plotWrap .scaleTick.q3{top:calc(25% + 6px)}.plotWrap .scaleTick.q1{top:calc(75% - 6px)}.plotWrap .scaleTick.bottom{top:calc(100% - 12px);transform:translateY(-50%)}.plotWrap .mark.edgeTop,.plotWrap .mark.edgeBottom{left:90px;right:90px;height:4px;border-radius:8px;transform:translateY(-2px)}.track .fill{bottom:10px}.capShade{position:absolute;left:0;right:0;height:10px;background:repeating-linear-gradient(135deg,#208ff199 0 4px,#55bcff99 4px 8px);z-index:1}.capShade.topCap{top:0;border-radius:6px 6px 0 0}.capShade.bottomCap{bottom:0;border-radius:0 0 6px 6px}.capShade[hidden]{display:none}
.plotWrap .scaleTick.top:after,.plotWrap .scaleTick.bottom:after{display:block}
.plotWrap:after{content:'';position:absolute;left:90px;right:90px;top:0;bottom:0;border:2px solid #adbcc5;border-radius:8px;z-index:8;pointer-events:none}
.track .fill{background:linear-gradient(0deg,#145caa,#22a9f6);transition:none}
.statusIcon{flex:none;display:flex;align-items:center;justify-content:center;line-height:0}.statusIcon svg{display:block;width:19px;height:19px;overflow:visible}.calStatus .statusIcon path{fill:none;stroke:#11251b;stroke-width:3.2;stroke-linecap:round;stroke-linejoin:round}.torqueStatus .statusIcon path{fill:#111}.moveStatus .statusIcon circle{fill:#192126}
.lowerTelemetry{margin-top:auto}.readout .positionRow{padding:10px 13px;margin-bottom:8px}.readout .positionRow .value{font-size:23px}.readout .positionRow header{margin-bottom:3px}
.manual,.plotCol,.readout{gap:12px}.manual>.panelTitle,.plotCol>.panelTitle,.readout>.panelTitle{height:48px;margin-bottom:0;box-sizing:border-box}.manual>.switchRow,.readout>.switchRow,.plotCol>.auto{height:68px;min-height:68px;box-sizing:border-box;margin:0}
.readout>.livePair{height:125px;min-height:125px}.readout>.livePair .liveLine{justify-content:center}
#all{background:#171c1f;border:1px solid #323d42;border-radius:12px;padding:20px;box-shadow:inset 0 0 30px #ffffff05}.groupControls{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:12px}.groupControls button.small{min-height:58px;font-size:18px;font-weight:700}
/* Restrained, self-contained dashboard styling; no remote fonts or icons. */
:root{color-scheme:dark;background:#000;color:#e8e8e8;font:15px/1.45 system-ui,-apple-system,"Segoe UI",sans-serif}
h1{font-size:30px;font-weight:650;letter-spacing:-.025em}h2{font-size:20px;font-weight:650;letter-spacing:-.015em}.eyebrow{color:#a0a0a0;letter-spacing:.08em;font-weight:650}.muted{color:#aaa}
#all,.manual,.plotCol,.readout{background:#1c1c1c;border-color:#383838;box-shadow:none}.panelTitle{font-size:21px;font-weight:650;letter-spacing:-.02em}.panelSub{font-size:17px;font-weight:650}
.switchRow,.sliderBox,.tiltBox,.positionRow,.statusBox,.telemetryGrid .metric,.readout .liveLine{background:#252525;border-color:#3c3c3c}.manualRow button{background:#2d2d2d;border-color:#494949;font-weight:600}.manualRow button:hover:not(:disabled){background:#393939}
.groupControls button.small,.tiltChoices button.small{background:#323232;border-color:#4c4c4c;color:#e8e8e8;font-weight:600}.groupControls button.small:hover:not(:disabled),.tiltChoices button.small:hover:not(:disabled){background:#404040;border-color:#6a9fbd}.groupControls button.small{font-size:17px}
.plotCol>.primary{background:#246e9d;border-color:#3986b1}.plotCol>.danger{background:#874349;border-color:#a45b60;color:#fff3f3}.badge{background:#323232;color:#ccc}
.sliderValue{color:#74b4d9}.sliderBox input[type=range]{accent-color:#65a9d0}.meter{background:#444}.meter span{background:#65a9d0}.positionRow .value{font-weight:700}.positionRow .kind{font-weight:550}.positionRow .blue{color:#7bb8df}.positionRow .green{color:#76c99a}
.track{background:#282828}.track .fill{background:#207daf}.mark.green,.markAnnotation.green{color:#6acb8c}.mark.blue,.markAnnotation.blue{color:#6db7e1}.mark.red,.markAnnotation.red{color:#d7787d}.mark.current{background:#d0d0d0}.scaleTick,.plotTop,.plotBottom{color:#c1c1c1}
.statusIcon{background:#777}.statusBox small{color:#bcbcbc}.statusBox strong{color:#ededed}.statusBox.good strong{color:#6acb8c}.switchRow input{background:#555}.manualRow .stopButton{background:#303030}.panelSub,.sliderStack,.details{border-color:#3c3c3c}.direction select,.positionRow input{background:#252525;border-color:#4a4a4a}.plotWrap:after{border-color:#aaa}.scaleTick:after{border-color:#aaa}
.plotWrap .track,.plotWrap .mark,.plotWrap .mark.edgeTop,.plotWrap .mark.edgeBottom{left:80px}
.plotWrap:after{left:80px}
.plotTop,.plotBottom{margin-left:80px}
.plotWrap .scaleTick:after{right:-7px}
.plotCol>.plotTop{margin-top:auto}
@media(max-width:600px){.groupControls{grid-template-columns:repeat(3,minmax(0,1fr))}}
@media(max-width:900px){.calGrid{grid-template-columns:1fr 1fr}.readout{grid-column:1/-1}}@media(max-width:600px){.calGrid{grid-template-columns:1fr}.readout{grid-column:auto}.plotWrap{height:450px}.manualRow button{height:100px}}
@media(max-width:900px){.calGrid{grid-template-columns:1fr 1fr}.readout{grid-column:1/-1}.card{padding:15px}}
@media(max-width:600px){.calGrid{grid-template-columns:1fr}.readout{grid-column:auto}.plotWrap{height:330px}.manualRow{grid-template-columns:52px 1fr}}
</style></head><body><main>
<header><div><div class="eyebrow">Common Area Blinds</div><h1>Servo Settings</h1></div><div id="connection" class="connection">Connecting…</div></header>
<section id="all" class="card" hidden></section><div id="cards" class="stack" style="margin-top:18px"></div>
</main><div id="toast" class="toast" hidden></div><script>
const $=s=>document.querySelector(s), esc=s=>encodeURIComponent(s), fmt=n=>Number.isFinite(n)?Math.round(n).toLocaleString():'—';
const root=$('#cards');let last={}, busy=false, toastTimer;
function toast(message){const el=$('#toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,4000)}
function button(id,label,action,extra=''){return `<button data-id="${id}" data-action="${action}" ${extra}>${label}</button>`}
function makeCard(s){const id=s.id;const article=document.createElement('article');article.className='card';article.id=`blind-${id}`;article.innerHTML=`
  <div class="cardhead"><div><div class="eyebrow">Servo ${id}</div><h2>Blind ${id}</h2></div></div>
  <div class="calGrid"><div class="manual"><div class="panelTitle">Manual Control</div><label class="switchRow">Manual Control <input class="manualToggle" type="checkbox" data-id="${id}"></label>
    <div class="manualRow">${button(id,'↑','jog-up','class="arrow" aria-label="Jog up"')}${button(id,'Set Up','set-up','class="set"')}</div>
    <div class="manualRow">${button(id,'■','stop','class="arrow stopButton" aria-label="Stop movement and auto calibration"')}${button(id,'Set Middle','set-middle','class="set"')}</div>
    <div class="manualRow">${button(id,'↓','jog-down','class="arrow" aria-label="Jog down"')}${button(id,'Set Down','set-down','class="set"')}</div>
    <div class="sliderBox"><div class="sliderHead"><span>Manual Jog</span><strong class="sliderValue jogValue">—</strong></div><input class="jog" type="range" min="1" max="2520" step="1" data-id="${id}" data-setting="jog"><div class="rangeEnds"><span>1°</span><span class="jogMax">2520°</span></div></div>
    <div class="tiltBox"><div class="sliderHead"><span>Blind Tilt</span><strong class="sliderValue tiltValue">—</strong></div><div class="tiltChoices">${[0,25,50,75,100].map(p=>button(id,`${p}%`,`tilt-${p}`,'class="small"')).join('')}</div></div>
    <div class="sliderStack">
    <div class="sliderBox"><div class="sliderHead"><span>Acceleration</span><strong class="sliderValue accelerationValue">—</strong></div><input class="acceleration" type="range" min="0" max="254" step="1" data-id="${id}" data-setting="acceleration"><div class="rangeEnds"><span>0</span><span class="accelerationMax">—</span></div></div>
    <div class="sliderBox"><div class="sliderHead"><span>Startup Force / Punch</span><strong class="sliderValue startupForceValue">—</strong></div><input class="startupForce" type="range" min="0" max="100" step="1" data-id="${id}" data-setting="startupForce"><div class="rangeEnds"><span>0%</span><span>100%</span></div></div>
    <div class="sliderBox"><div class="sliderHead"><span>Speed Limit</span><strong class="sliderValue speedLimitValue">—</strong></div><input class="speedLimit" type="range" min="0" max="360" step="1" data-id="${id}" data-setting="speedLimit"><div class="rangeEnds"><span>0°/s</span><span class="speedLimitMax">360°/s</span></div></div>
    <div class="sliderBox"><div class="sliderHead"><span>Torque Limit</span><strong class="sliderValue torqueLimitValue">—</strong></div><input class="torqueLimit" type="range" min="0" max="100" step="1" data-id="${id}" data-setting="torqueLimit"><div class="rangeEnds"><span>0%</span><span>100%</span></div></div>
    </div>
  </div><div class="plotCol"><div class="panelTitle">Calibration</div>
    ${button(id,'Auto calibrate','auto','class="primary auto"')}
    ${button(id,'↺ Reset Calibration','reset','class="danger reset"')}
    <div class="statusStack"><div class="statusBox calStatus"><span class="statusIcon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12.5 10 17l9-10"/></svg></span><span class="statusText"><small>Calibration Status</small><strong class="calStatusText">—</strong></span></div><div class="statusBox torqueStatus"><span class="statusIcon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m13 2-8 11h6l-1 9 9-12h-6z"/></svg></span><span class="statusText"><small>Torque</small><strong class="torqueStatusText">—</strong></span></div><div class="statusBox moveStatus"><span class="statusIcon"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="5"/></svg></span><span class="statusText"><small>Moving</small><strong class="moveStatusText">—</strong></span></div></div>
    <div class="plotTop"><span class="plotTopLabel">Fully Up (100%)</span><br><span class="plotTopValue">—</span></div>
    <div class="plotWrap"><span class="scaleTick top">100%</span><span class="scaleTick q3">75%</span><span class="scaleTick mid">50%</span><span class="scaleTick q1">25%</span><span class="scaleTick bottom">0%</span><div class="track"><div class="fill"></div><div class="capShade topCap" hidden title="Upper overextend move"></div><div class="capShade bottomCap" hidden title="Lower overextend move"></div></div><div class="markers"></div></div>
    <div class="plotBottom"><span class="plotBottomLabel">Fully Down (0%)</span><br><span class="plotBottomValue">—</span></div>
    <label class="direction">Negative direction<select data-id="${id}" class="directionSelect"><option>Negative is down</option><option>Negative is up</option></select></label>
  </div><div class="readout"><div class="panelTitle">Position Data</div><label class="switchRow">Edit Positions <input class="editToggle" type="checkbox" data-id="${id}"></label>
    <div class="livePair"><div class="liveLine"><span>Live Encoder</span><strong class="currentValue">—</strong></div>
    <div class="liveLine"><span>Live Target</span><strong class="targetValue">—</strong></div></div>
    <div class="positionEditors">${[['up','Up'],['three_quarter','75%'],['middle','50%'],['quarter','25%'],['down','Down']].map(([key,label])=>`<div class="positionRow"><header><strong>${label}</strong><span class="kind ${key}Kind">—</span></header><div class="value ${key}Value">—</div><input class="${key}Edit" inputmode="numeric" aria-label="${label} encoder position" hidden></div>`).join('')}${button(id,'Save Positions','save-positions','class="savePositions primary" hidden')}</div>
    <div class="panelSub">Motor Telemetry</div><div class="telemetryGrid"><div class="metric"><small>Current</small><strong class="currentAmps">—</strong><div class="meter"><span class="currentMeter"></span></div><div class="meterEnds"><span>0 A</span><span>3 A</span></div></div><div class="metric"><small>Voltage</small><strong class="voltage">—</strong><div class="meter"><span class="voltageMeter"></span></div><div class="meterEnds"><span>0 V</span><span>15 V</span></div></div><div class="metric"><small>Torque Output</small><strong class="load">—</strong><div class="meter"><span class="loadMeter"></span></div><div class="meterEnds"><span>0%</span><span>100%</span></div></div><div class="metric"><small>Speed Output</small><strong class="speed">—</strong><div class="meter"><span class="speedMeter"></span></div><div class="meterEnds"><span>0°/s</span><span>360°/s</span></div></div></div><div class="telemetryGrid lowerTelemetry"><div class="metric"><small>Temperature</small><strong class="temperature">—</strong><div class="meter"><span class="temperatureMeter"></span></div><div class="meterEnds"><span>0°C</span><span>80°C</span></div></div><div class="metric"><small>Servo Status</small><strong class="servoStatus">—</strong><div class="meter"><span class="servoStatusMeter"></span></div><div class="meterEnds"><span>0</span><span>255</span></div></div></div>
  </div></div>
  `;
  root.append(article);return article}
function num(v,unit='',digits=1){return Number.isFinite(v)?`${v.toFixed(digits)}${unit}`:'—'}
function render(s){let card=$(`#blind-${s.id}`)||makeCard(s);last[s.id]=s;const set=(cls,val)=>card.querySelector('.'+cls).textContent=val;
  const valid=Number.isFinite(s.position), full=(s.mask&5)===5&&s.down!==s.up;
  const scale=full?{down:s.down,up:s.up}:(()=>{const pts=[0,s.position,s.target,...[[1,s.down],[2,s.middle],[4,s.up]].filter(([bit])=>s.mask&bit).map(([,v])=>v)].filter(Number.isFinite);let lo=Math.min(...pts),hi=Math.max(...pts);if(hi-lo<4096){const mid=(lo+hi)/2;lo=mid-2048;hi=mid+2048}return s.negative_is_down?{down:lo,up:hi}:{down:hi,up:lo}})();
  const pct=v=>Math.max(0,Math.min(1,(v-scale.down)/(scale.up-scale.down))),displayPct=v=>s.negative_is_down?pct(v):1-pct(v),plotHeight=card.querySelector('.plotWrap').clientHeight,graphHeight=plotHeight-24,markers=[];
  const add=(v,label,color,side='left',extra='')=>{if(!Number.isFinite(v))return;const top=(12+(1-displayPct(v))*graphHeight).toFixed(1);markers.push(`<div class="mark ${color} ${extra}" style="top:${top}px"></div>${label?`<span class="markAnnotation ${color}" style="top:${top}px"><i class="markPointer"></i><span class="markNumber">${label}</span></span>`:''}`)};
  if(s.mask&4)add(s.up,fmt(s.up),'green','left',s.up===0?'striped':'');if((s.mask&7)===7)add(s.three_quarter,fmt(s.three_quarter),s.quarter_manual_mask&2?'green':'blue');if(s.mask&2)add(s.middle,fmt(s.middle),s.middle_calculated?'blue':'green','right');if((s.mask&7)===7)add(s.quarter,fmt(s.quarter),s.quarter_manual_mask&1?'green':'blue');if(s.mask&1)add(s.down,fmt(s.down),'green','left',s.down===0?'striped':'');
  if(!((s.mask&4)&&s.up===0)&&!((s.mask&1)&&s.down===0))add(0,'','red','left');if(valid)add(s.position,'','current');if(s.moving&&Number.isFinite(s.target))add(s.target,'TARGET','blue','right','target');
  card.querySelector('.markers').innerHTML=markers.join('');const fill=card.querySelector('.fill');fill.style.height=`${valid?(2+pct(s.position)*graphHeight).toFixed(1):0}px`;fill.style.bottom=s.negative_is_down?'10px':'auto';fill.style.top=s.negative_is_down?'auto':'10px';
  card.querySelector('.topCap').hidden=!(s.overextend_active&&s.overextend_endpoint===(s.negative_is_down?s.up:s.down));card.querySelector('.bottomCap').hidden=!(s.overextend_active&&s.overextend_endpoint===(s.negative_is_down?s.down:s.up));
  set('currentValue',valid?`${fmt(s.position)} counts${full&&(s.position<Math.min(s.down,s.up)||s.position>Math.max(s.down,s.up))?' · capped':''}`:'Unavailable');
  set('targetValue',`${fmt(s.target)} counts`);
  for(const [name,value] of [['top',s.negative_is_down?100:0],['q3',s.negative_is_down?75:25],['mid',50],['q1',s.negative_is_down?25:75],['bottom',s.negative_is_down?0:100]])card.querySelector('.scaleTick.'+name).textContent=`${value}%`;
  set('plotTopLabel',s.negative_is_down?'Fully Up (100%)':'Fully Down (0%)');set('plotBottomLabel',s.negative_is_down?'Fully Down (0%)':'Fully Up (100%)');set('plotTopValue',s.negative_is_down?(s.mask&4?`(${fmt(s.up)})`:'—'):(s.mask&1?`(${fmt(s.down)})`:'—'));set('plotBottomValue',s.negative_is_down?(s.mask&1?`(${fmt(s.down)})`:'—'):(s.mask&4?`(${fmt(s.up)})`:'—'));
  set('calStatusText',s.status==='Ok'?'Valid (No Errors)':s.status);set('torqueStatusText',s.torque_enabled?'Enabled':'Disabled');set('moveStatusText',s.moving?'Moving':'Idle (Not Moving)');
  card.querySelector('.calStatus').classList.toggle('good',s.status==='Ok');card.querySelector('.torqueStatus').classList.toggle('good',s.torque_enabled);card.querySelector('.moveStatus').classList.toggle('good',s.moving);
  card.querySelectorAll('.set,.arrow:not(.stopButton)').forEach(el=>el.disabled=!s.manual_control||s.auto_active);card.querySelector('.stopButton').disabled=!s.moving&&!s.auto_active;
  card.querySelector('.manualToggle').checked=s.manual_control;card.querySelector('.manualToggle').disabled=s.auto_active;
  card.querySelector('.editToggle').checked=s.edit_positions;card.querySelector('.editToggle').disabled=s.auto_active;
  card.querySelector('.auto').disabled=s.calibrated||s.auto_active;
  card.querySelector('.directionSelect').disabled=(s.calibrated&&!s.manual_control)||s.auto_active;card.querySelector('.directionSelect').value=s.negative_is_down?'Negative is down':'Negative is up';
  for(const [key,bit] of [['up',4],['three_quarter',7],['middle',2],['quarter',7],['down',1]]){const present=(s.mask&bit)===bit,kind=card.querySelector('.'+key+'Kind'),isQuarter=key==='quarter'||key==='three_quarter',isManual=isQuarter?!!(s.quarter_manual_mask&(key==='quarter'?1:2)):s.positions_manual,isCalculated=isQuarter?!isManual:key==='middle'&&s.middle_calculated;kind.textContent=present?(isManual?'Manual':isCalculated?'Calculated':'Calibrated'):'Unset';kind.className=`kind ${key}Kind ${isCalculated?'blue':'green'}`;set(key+'Value',present?`${fmt(s[key])} counts`:'—');const input=card.querySelector('.'+key+'Edit');input.hidden=!s.edit_positions;if(document.activeElement!==input)input.value=present?s[key]:''}card.querySelector('.savePositions').hidden=!s.edit_positions;
  for(const [cls,max,unit] of [['jog',s.jog_max??2520,'°'],['speedLimit',s.speed_limit_max??360,'°/s'],['acceleration',s.acceleration_max??254,'']]){card.querySelector('.'+cls).max=max;set(cls+'Max',`${max}${unit}`)}
  const notEditing=cls=>document.activeElement!==card.querySelector('.'+cls);for(const [cls,value] of [['jog',s.jog],['speedLimit',s.speed_limit],['acceleration',s.acceleration],['startupForce',s.startup_force],['torqueLimit',s.torque_limit]]){if(notEditing(cls))card.querySelector('.'+cls).value=value;set(cls+'Value',`${value}${cls==='jog'?'°':cls==='speedLimit'?'°/s':cls==='startupForce'||cls==='torqueLimit'?'%':''}`)}
  set('speed',num(s.speed,' °/s'));set('load',num(s.load,' %'));set('voltage',num(s.voltage,' V'));set('currentAmps',num(s.current,' A',3));
  set('temperature',num(s.temperature,' °C',0));set('servoStatus',Number.isFinite(s.servo_status)?fmt(s.servo_status):'—');
  for(const [name,value,max] of [['current',s.current,3],['voltage',s.voltage,15],['load',Math.abs(s.load),100],['speed',Math.abs(s.speed),360],['temperature',s.temperature,80],['servoStatus',s.servo_status,255]])card.querySelector('.'+name+'Meter').style.width=`${Number.isFinite(value)?Math.max(0,Math.min(100,value/max*100)):0}%`;
  set('tiltValue',num(s.tilt*100,' %',0));
}
function renderAll(d){const all=$('#all');if(!Number.isFinite(d.all_tilt))return;all.hidden=false;
 all.innerHTML=`<div class="cardhead"><div><div class="eyebrow">Group control</div><h2>All Blinds</h2></div><span class="badge">${Math.round(d.all_tilt*100)}% tilt</span></div><div class="groupControls">${[0,25,50,75,100].map(p=>button(0,`${p}%`,`tilt-${p}`,'class="small"')).join('')}${button(0,'Stop','stop','class="small"')}</div>`}
async function poll(){if(busy)return;busy=true;try{const response=await fetch('/sts3215/state',{cache:'no-store'});if(!response.ok)throw Error('Device did not return state');const data=await response.json();data.servos.forEach(render);renderAll(data);const conn=$('#connection');conn.textContent='Live';conn.className='connection live'}catch(e){const conn=$('#connection');conn.textContent='Reconnecting…';conn.className='connection'}finally{busy=false}}
async function post(url){const response=await fetch(url,{method:'POST'});if(!response.ok)throw Error(`Command failed (${response.status})`);setTimeout(poll,200)}
document.addEventListener('click',async e=>{const b=e.target.closest('button[data-action]');if(!b)return;const id=Number(b.dataset.id),action=b.dataset.action,s=last[id],prefix=`Blind ${id}`;
 try{if(action==='reset'){if(!confirm(`Reset calibration for ${prefix}? Its saved positions will be cleared.`))return;await post(`/button/${esc(prefix+' Reset Calibration')}/press`)}
 else if(action==='auto')await post(`/button/${esc(prefix+' Auto Calibrate')}/press`);
 else if(action==='jog-up'||action==='jog-down'){const forward=action==='jog-up'?s.negative_is_down:!s.negative_is_down;await post(`/button/${esc(prefix+(forward?' Jog Forward':' Jog Reverse'))}/press`)}
 else if(action.startsWith('set-')){const suffix={'set-up':' Set Fully Up','set-middle':' Set Middle','set-down':' Set Fully Down'}[action];await post(`/button/${esc(prefix+suffix)}/press`)}
 else if(action.startsWith('tilt-'))await post(`/cover/${esc(id?prefix:'All Blinds')}/set?tilt=${Number(action.slice(5))/100}`);
 else if(action==='stop')await post(`/cover/${esc(id?prefix:'All Blinds')}/stop`);
 else if(action==='save-positions'){const card=$(`#blind-${id}`),values={};for(const key of ['down','quarter','middle','three_quarter','up']){const raw=card.querySelector('.'+key+'Edit').value.trim();if(!/^[+-]?\d+$/.test(raw))throw Error('Positions must be whole numbers');const n=Number(raw);if(!Number.isSafeInteger(n)||n< -2147483648||n>2147483647)throw Error('Position is outside the supported range');values[key]=n}const v=['down','quarter','middle','three_quarter','up'].map(key=>values[key]);if(!(v.every((n,i)=>i===0||v[i-1]<n)||v.every((n,i)=>i===0||v[i-1]>n)))throw Error('Positions must be in order from down to up');await control(id,'positions',values);toast('Manual positions saved')}
 }catch(error){toast(error.message)}});
async function control(id,action,values){const body=new URLSearchParams({id:String(id),action,...Object.fromEntries(Object.entries(values).map(([k,v])=>[k,String(v)]))});const response=await fetch('/sts3215/control',{method:'POST',body});if(!response.ok)throw Error(await response.text());await poll()}
const settingNames={jog:' Jog Increment',acceleration:' Acceleration',speedLimit:' Speed Limit',torqueLimit:' Torque Limit'};
document.addEventListener('input',e=>{const el=e.target;if(el.matches('input[data-setting]')){const unit=el.dataset.setting==='jog'?'°':el.dataset.setting==='speedLimit'?'°/s':el.dataset.setting==='startupForce'||el.dataset.setting==='torqueLimit'?'%':'';el.closest('.sliderBox').querySelector('.sliderValue').textContent=el.value+unit}});
document.addEventListener('change',async e=>{const el=e.target,id=Number(el.dataset.id);try{if(el.matches('input[data-setting]')){if(el.dataset.setting==='startupForce')await control(id,'startup_force',{value:el.value});else await post(`/number/${esc(`Blind ${id}`+settingNames[el.dataset.setting])}/set?value=${esc(el.value)}`)}else if(el.matches('.directionSelect'))await post(`/select/${esc(`Blind ${id} Negative Direction`)}/set?option=${esc(el.value)}`);else if(el.matches('.manualToggle'))await control(id,'manual',{value:el.checked?1:0});else if(el.matches('.editToggle'))await control(id,'edit',{value:el.checked?1:0})}catch(error){toast(error.message);poll()}});
poll();setInterval(poll,1000);
</script></body></html>)stsweb";
